---
apiVersion: v1
kind: Service
metadata:
  namespace: ernado
  name: teletok
  labels:
    app: teletok
    prometheus: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8090
      name: metrics
  selector:
    app: teletok
  sessionAffinity: None
