// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/validate"
)

func (s Data) Validate() error {
	var failures []validate.FieldError
	if err := func() error {
		if s.VideoAuthorDiggCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoAuthorDiggCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_author_diggCount",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoAuthorFollowerCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoAuthorFollowerCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_author_followerCount",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoAuthorFollowingCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoAuthorFollowingCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_author_followingCount",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoAuthorHeartCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoAuthorHeartCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_author_heartCount",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoAuthorVideoCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoAuthorVideoCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_author_videoCount",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoCommentCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoCommentCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_comment_count",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoCreateTime.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoCreateTime.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_create_time",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoDiggCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoDiggCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_digg_count",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoDownloadCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoDownloadCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_download_count",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoMusicID.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoMusicID.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_music_id",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoPlayCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoPlayCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_play_count",
			Error: err,
		})
	}
	if err := func() error {
		if s.VideoShareCount.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.VideoShareCount.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "video_share_count",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
